# Generated by Django 5.1.7 on 2025-03-26 10:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='page',
            field=modelcluster.fields.ParentalKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='applications.careerspage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetailpage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pages', to='applications.jobpost'),
        ),
    ]
