# Generated by Django 5.1.7 on 2025-04-08 17:26

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_remove_jobpost_page_remove_jobapplicationfield_page_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTrackingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the page')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, help_text='Application deadline')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when application was submitted')),
                ('review_date', models.DateTimeField(blank=True, help_text='Date when application is under review', null=True)),
                ('interview_date', models.DateTimeField(blank=True, help_text='Date when interview is scheduled', null=True)),
                ('decision_date', models.DateTimeField(blank=True, help_text='Date when decision is made', null=True)),
                ('carousel_title_1', models.CharField(default='Welcome to Application Tracking', max_length=100)),
                ('carousel_text_1', models.TextField(default='Track your application progress in real-time')),
                ('carousel_title_2', models.CharField(default='Stay Updated', max_length=100)),
                ('carousel_text_2', models.TextField(default='Get instant notifications about your application status')),
                ('carousel_title_3', models.CharField(default='Easy to Use', max_length=100)),
                ('carousel_text_3', models.TextField(default='Simple and intuitive interface for tracking applications')),
            ],
            options={
                'verbose_name': 'Application Tracking Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
