# Generated by Django 5.1.7 on 2025-04-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ApplicationFormField',
        ),
        migrations.DeleteModel(
            name='ApplicationTrackingPage',
        ),
    ]
