# Generated by Django 5.1.7 on 2025-04-08 18:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtrackingpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
