# Generated by Django 5.1.7 on 2025-04-09 05:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationtrackingpage_thank_you_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='applications.applicationtrackingpage'),
        ),
    ]
