# Generated by Django 5.1.7 on 2025-04-09 05:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_applicationformfield_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_text_1',
        ),
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_text_2',
        ),
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_text_3',
        ),
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_title_1',
        ),
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_title_2',
        ),
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='carousel_title_3',
        ),
        migrations.AddField(
            model_name='applicationtrackingpage',
            name='content',
            field=wagtail.fields.StreamField([('carousel', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No Link'), ('page', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Select the type of link you want to add'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page to link to', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter an external URL to link to', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Read more', 'help_text': 'Text to display on the link button', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('link_type', 3), ('page_link', 4), ('external_link', 5), ('link_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-rotate the carousel items', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show the carousel indicators', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show the carousel navigation arrows', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('items', 8), ('auto_play', 9), ('show_indicators', 10), ('show_arrows', 11)]], {})}),
        ),
    ]
