# Generated by Django 5.1.7 on 2025-04-09 07:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_applicationtrackingpage_carousel_text_1_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Text to display at the top of the page')),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Additional content to display on the landing page')),
            ],
            options={
                'verbose_name': 'Application Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='applicationtrackingpage',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='Page to redirect to after form submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
