# Generated by Django 5.1.7 on 2025-04-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_applicationlandingpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrackingpage',
            name='landing_page',
        ),
        migrations.DeleteModel(
            name='ApplicationLandingPage',
        ),
    ]
