version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ProductionDockerfile/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    restart: always

    ports:
    - "8000:8000"

  
    env_file:
      - .env.prod



volumes:
  postgres_data:
  static_volume:
  media_volume:
