# Generated by Django 5.1.7 on 2025-03-13 11:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='body2',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 8), ('quote', 10), ('button', 13), ('video', 15), ('document', 18), ('cta', 22), ('accordion', 26), ('two_column', 31), ('carousel', 34), ('embed', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')]}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for screen readers', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt_text', 6), ('link', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('quote', 9), ('attribution', 5)]], {}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')]}), 13: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 11), ('style', 12)]], {}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('video', 14), ('caption', 5)]], {}), 16: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 17: ('wagtail.blocks.TextBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('document', 16), ('title', 5), ('description', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'required': True}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary')]}), 22: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 19), ('button_text', 20), ('button_link', 11), ('background_color', 21)]], {}), 23: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('items', 25)]], {}), 27: ('wagtail.blocks.RichTextBlock', (), {}), 28: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 27), ('image', 8), ('button', 13)]], {'icon': 'arrow-left', 'label': 'Left column content'}), 29: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 27), ('image', 8), ('button', 13)]], {'icon': 'arrow-right', 'label': 'Right column content'}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('50-50', '50% / 50%'), ('33-67', '33% / 67%'), ('67-33', '67% / 33%')], 'help_text': 'Choose the width distribution of the columns'}), 31: ('wagtail.blocks.StructBlock', [[('left_column', 28), ('right_column', 29), ('column_distribution', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('image', 4), ('title', 5), ('text', 17), ('link', 7), ('link_text', 5)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('items', 33)]], {}), 35: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'})}, null=True),
        ),
    ]
