# Generated by Django 5.1.7 on 2025-03-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsindexpage_carousel_alter_newsarticlepage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsindexpage',
            name='carousel',
        ),
    ]
