# Generated by Django 5.1.7 on 2025-04-07 04:38

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_newsarticlepage_body2'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
