# Generated by Django 5.1.7 on 2025-04-08 15:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_newsarticlepage_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='SubscribeBlock',
            field=wagtail.fields.StreamField([('subscribe', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to our newsletter', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Stay updated with our latest news and updates.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Your email address', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Thank you for subscribing!', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary')]}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('placeholder_text', 2), ('button_text', 3), ('success_message', 4), ('background_color', 5)]], {})}, null=True),
        ),
    ]
