# Generated by Django 5.1.7 on 2025-03-14 12:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='top_articles',
            field=wagtail.fields.StreamField([('top_articles', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Top Articles', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'help_text': 'Choose how many articles to display', 'max_value': 10, 'min_value': 1, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article featured images', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article dates', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show or hide the article authors', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('number_of_articles', 1), ('show_images', 2), ('show_date', 3), ('show_author', 4)]], {})}, null=True),
        ),
    ]
