# Generated by Django 5.1.7 on 2025-03-15 04:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_top_articles_homepage_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='accordion',
            field=wagtail.fields.StreamField([('accordion', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('items', 3)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=wagtail.fields.StreamField([('image', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for screen readers', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('alt_text', 2), ('link', 3)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe',
            field=wagtail.fields.StreamField([('subscribe', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to our newsletter', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Stay updated with our latest news and updates.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Your email address', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Thank you for subscribing!', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary')]}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('placeholder_text', 2), ('button_text', 3), ('success_message', 4), ('background_color', 5)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_articles',
            field=wagtail.fields.StreamField([('top_articles', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Top Articles', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'help_text': 'Choose how many articles to display', 'max_value': 10, 'min_value': 1, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article featured images', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article dates', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show or hide the article authors', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('number_of_articles', 1), ('show_images', 2), ('show_date', 3), ('show_author', 4)]], {})}, null=True),
        ),
    ]
