# Generated by Django 5.1.7 on 2025-03-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_accordion_homepage_image_homepage_subscribe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body2',
        ),
    ]
