# Generated by Django 5.1.7 on 2025-04-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_accordion_remove_homepage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
