# Generated by Django 5.1.7 on 2025-04-02 05:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_main_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='main_body',
            field=wagtail.fields.StreamField([('top_articles', 5), ('subscribe', 12), ('accordion', 17), ('image', 22), ('body', 23), ('testimonials', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Top Articles', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'help_text': 'Choose how many articles to display', 'max_value': 10, 'min_value': 1, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article featured images', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show or hide the article dates', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show or hide the article authors', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('number_of_articles', 1), ('show_images', 2), ('show_date', 3), ('show_author', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to our newsletter', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'default': 'Stay updated with our latest news and updates.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Your email address', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Thank you for subscribing!', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('placeholder_text', 8), ('button_text', 9), ('success_message', 10), ('background_color', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('items', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for screen readers', 'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19), ('alt_text', 20), ('link', 21)]], {}), 23: ('wagtail.blocks.RichTextBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'What People Say', 'required': False}), 25: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Add a YouTube video URL', 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the person giving testimonial', 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role or title of the person', 'required': False}), 28: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short quote or testimonial text', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('video', 25), ('name', 26), ('role', 27), ('quote', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'help_text': 'Add between 1 and 4 video testimonials', 'max_num': 4, 'min_num': 1}), 31: ('wagtail.blocks.StructBlock', [[('title', 24), ('testimonials', 30)]], {})}, null=True),
        ),
    ]
