# Generated by Django 5.1.7 on 2025-04-02 05:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_main_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='notification_banner',
            field=wagtail.fields.StreamField([('notification_banner', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Notification text content', 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable or disable this notification', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information (Blue)'), ('warning', 'Warning (Yellow)'), ('danger', 'Alert (Red)'), ('success', 'Success (Green)'), ('primary', 'Primary (Brand Color)')], 'help_text': 'Choose the style of notification'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional Font Awesome icon name (e.g. 'fa-info-circle')", 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Allow users to dismiss this notification', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link text', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 0), ('is_enabled', 1), ('style', 2), ('icon', 3), ('is_dismissible', 4), ('link_text', 5), ('link_url', 6)]], {})}, help_text='Add a notification banner to the top of the page', null=True),
        ),
    ]
