# Generated by Django 5.1.7 on 2025-04-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_navigationsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
    ]
