# Generated by Django 5.1.7 on 2025-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='label_ar',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='label_so',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
    ]
