# Generated by Django 5.1.7 on 2025-03-26 13:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Main Department', 'verbose_name_plural': 'Main Departments'},
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='content',
            field=wagtail.fields.StreamField([('carousel', 12), ('statistics', 20)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No Link'), ('page', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Select the type of link you want to add'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page to link to', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter an external URL to link to', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Read more', 'help_text': 'Text to display on the link button', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('link_type', 3), ('page_link', 4), ('external_link', 5), ('link_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-rotate the carousel items', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show the carousel indicators', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show the carousel navigation arrows', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('items', 8), ('auto_play', 9), ('show_indicators', 10), ('show_arrows', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the statistics section', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "The main number/percentage to display (e.g. '97%', '286')", 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'The description text below the number', 'required': True}), 16: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check if this number represents a percentage', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('number', 14), ('description', 15), ('is_percentage', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'help_text': 'Add between 1 and 4 statistics', 'max_num': 4, 'min_num': 1}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light Blue'), ('dark', 'Deep Blue'), ('gradient', 'Blue Gradient'), ('transparent', 'Transparent')], 'help_text': 'Choose the background style for the statistics section'}), 20: ('wagtail.blocks.StructBlock', [[('title', 13), ('statistics', 18), ('background_style', 19)]], {})}),
        ),
    ]
