# Generated by Django 5.1.7 on 2025-04-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_financedepartmentpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinanceDepartmentPage',
            new_name='SubDepartmentPage',
        ),
    ]
