# Generated by Django 5.1.7 on 2025-04-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_rename_financedepartmentpage_subdepartmentpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepartmentpage',
            options={'verbose_name': 'Sub Department', 'verbose_name_plural': 'Sub Departments'},
        ),
    ]
